openapi: 3.0.3
info:
  title: Laravel
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/courses:
    get:
      summary: 'Display a listing of the resource.'
      operationId: displayAListingOfTheResource
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mxqwvjrhmskz
                  nullable: false
                instructor_name:
                  type: string
                  description: ''
                  example: doloribus
                  nullable: false
              required:
                - name
                - instructor_name
      security: []
  '/api/courses/{id}':
    put:
      summary: 'Update the specified resource in storage.'
      operationId: updateTheSpecifiedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: uown
                  nullable: false
                instructor_name:
                  type: string
                  description: ''
                  example: eveniet
                  nullable: false
              required:
                - name
                - instructor_name
      security: []
    delete:
      summary: 'Remove the specified resource from storage.'
      operationId: removeTheSpecifiedResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the course.'
        example: 20
        required: true
        schema:
          type: integer
  /api/lessons:
    get:
      summary: 'Display a listing of the lessons.'
      operationId: displayAListingOfTheLessons
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created lesson in the database.'
      operationId: storeANewlyCreatedLessonInTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: untqdpnyiqdnrsdm
                  nullable: false
                course_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the courses table.'
                  example: sed
                  nullable: false
              required:
                - title
                - course_id
      security: []
  /api/lessons/create:
    get:
      summary: 'Show the form for creating a new lesson (not needed for API, so no implementation).'
      operationId: showTheFormForCreatingANewLessonnotNeededForAPISoNoImplementation
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Create method is not used in API.'
                properties:
                  message:
                    type: string
                    example: 'Create method is not used in API.'
      tags:
        - Endpoints
      security: []
  '/api/lessons/{id}':
    get:
      summary: 'Display the specified lesson.'
      operationId: displayTheSpecifiedLesson
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Lesson] 14'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Lesson] 14'
      tags:
        - Endpoints
      security: []
    put:
      summary: 'Update the specified lesson in the database.'
      operationId: updateTheSpecifiedLessonInTheDatabase
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: mjbuwgecvyyabpey
                  nullable: false
                course_id:
                  type: string
                  description: 'The <code>id</code> of an existing record in the courses table.'
                  example: magnam
                  nullable: false
              required:
                - title
                - course_id
      security: []
    delete:
      summary: 'Remove the specified lesson from storage.'
      operationId: removeTheSpecifiedLessonFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the lesson.'
        example: 14
        required: true
        schema:
          type: integer
  '/api/lessons/{lesson_id}/edit':
    get:
      summary: 'Show the form for editing the specified lesson (not needed for API, so no implementation).'
      operationId: showTheFormForEditingTheSpecifiedLessonnotNeededForAPISoNoImplementation
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\Lesson] 19'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\Lesson] 19'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: lesson_id
        description: 'The ID of the lesson.'
        example: 19
        required: true
        schema:
          type: integer
  /api/acheivements:
    get:
      summary: 'Display a listing of the achievements.'
      operationId: displayAListingOfTheAchievements
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created achievement in storage.'
      operationId: storeANewlyCreatedAchievementInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hpfubandkrrpacwsufba
                  nullable: false
                type:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: estzcepsnriahmwvrkx
                  nullable: false
                threshold:
                  type: integer
                  description: ''
                  example: 4
                  nullable: false
              required:
                - name
                - type
                - threshold
      security: []
  '/api/acheivements/{id}':
    put:
      summary: 'Update the specified achievement in storage.'
      operationId: updateTheSpecifiedAchievementInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: miiuzxnlrzggkk
                  nullable: false
                type:
                  type: string
                  description: 'Must not be greater than 50 characters.'
                  example: plqrdzfsaflu
                  nullable: false
                threshold:
                  type: integer
                  description: ''
                  example: 2
                  nullable: false
              required:
                - name
                - type
                - threshold
      security: []
    delete:
      summary: 'Remove the specified achievement from storage.'
      operationId: removeTheSpecifiedAchievementFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the acheivement.'
        example: 11
        required: true
        schema:
          type: integer
  /api/badges:
    get:
      summary: 'Display a listing of the badges.'
      operationId: displayAListingOfTheBadges
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example: []
      tags:
        - Endpoints
      security: []
    post:
      summary: 'Store a newly created badge in storage.'
      operationId: storeANewlyCreatedBadgeInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: iyrfrvbfpvbg
                  nullable: false
                required_achievements:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 83
                  nullable: false
              required:
                - name
                - required_achievements
      security: []
  '/api/badges/{id}':
    put:
      summary: 'Update the specified badge in storage.'
      operationId: updateTheSpecifiedBadgeInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: hsholvvxvynuf
                  nullable: false
                required_achievements:
                  type: integer
                  description: 'Must be at least 1.'
                  example: 66
                  nullable: false
              required:
                - name
                - required_achievements
      security: []
    delete:
      summary: 'Remove the specified badge from storage.'
      operationId: removeTheSpecifiedBadgeFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the badge.'
        example: 13
        required: true
        schema:
          type: integer
  '/api/courses/{course_id}/{user_id}':
    post:
      summary: ''
      operationId: postApiCoursesCourse_idUser_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: course_id
        description: 'The ID of the course.'
        example: 8
        required: true
        schema:
          type: integer
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: laudantium
        required: true
        schema:
          type: string
  '/api/users/{user_id}/achievements':
    get:
      summary: ''
      operationId: getApiUsersUser_idAchievements
      description: ''
      parameters: []
      responses:
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'No query results for model [App\Models\User] 10'
                properties:
                  message:
                    type: string
                    example: 'No query results for model [App\Models\User] 10'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 10
        required: true
        schema:
          type: integer
  '/api/{id}/comment':
    post:
      summary: 'Store a newly created resource in storage.'
      operationId: storeANewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: 'Must be at least 3 characters. Must not be greater than 1000 characters.'
                  example: xnlbfwwkdsqyaa
                  nullable: false
              required:
                - content
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the api.'
        example: quia
        required: true
        schema:
          type: string
tags:
  -
    name: Endpoints
    description: ''
